/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package cbb;


public class App {
    public static final String CLASS_COLLECTION_NAME = Utils.collectionName(Class.class);
    public static final String METHOD_COLLECTION_NAME = Utils.collectionName(BeanMethod.class);

    public static void main(String[] args) {
        DCPListener.main(args);
    }
}
