/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package cbb.servers;

import cbb.BeanException;
import cbb.BeanScope;
import cbb.Couchbeans;
import cbb.annotations.Scope;
import cbb.requests.EchoRequest;

import java.io.BufferedReader;
import java.io.InputStream;
import java.io.InputStreamReader;
import java.io.PrintStream;
import java.net.ServerSocket;
import java.net.Socket;

/**
 * This is a global bean, which means that it will be constructed and maintained from DCP stream on all nodes
 * except for those that are prohibited from owning it via `CBB_NODE_IGNORE_PACKAGES`
 * When constructed, this bean will wait for the `running` field to be set to true
 * and then launch an ICMP echo server on port `port` that registers all received
 * echo request as `EchoRequest` beans linked to the `EchoServer` singleton
 */
@Scope(BeanScope.GLOBAL)
public class EchoServer {
    private boolean running;
    private short port = 9000;

    private static transient Thread serverThread;

    private class ServerThread extends Thread {
        @Override
        public void run() {
            try (ServerSocket serverSocket = new ServerSocket(port)) {
                while (!(this.isInterrupted() || serverSocket.isClosed())) {
                    try (Socket socket = serverSocket.accept()) {
                        InputStream in = socket.getInputStream();
                        InputStreamReader inr = new InputStreamReader(in);
                        BufferedReader br = new BufferedReader(inr);
                        String message = br.readLine();
                        EchoRequest request = new EchoRequest(message, socket.getRemoteSocketAddress().toString());
                        Couchbeans.store(request);
                        Couchbeans.link(EchoServer.this, request);
                        PrintStream ps = new PrintStream(socket.getOutputStream());
                        ps.println(message);
                    }
                }
            } catch (Exception e) {
                BeanException.report(EchoServer.this, e);
            } finally {
                running = false;
                Couchbeans.store(EchoServer.this);
            }
        }
    }


    /**
     * This is a boolean value handler
     * CBB will call it when the corresponding field (running) is set to TRUE on an instance of the bean
     */
    private void whenRunning() {
        System.out.println("whenRunning");
        if (serverThread == null || !serverThread.isAlive()) {
            serverThread = new ServerThread();
            serverThread.start();
        }
    }

    /**
     * This is a boolean value handler
     * CBB will call it when the corresponding field (running) is set to FALSE on an instance of the bean
     */
    private void whenNotRunning() {
        System.out.println("whenNotRunning");
        serverThread.interrupt();
    }
}
