/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package cbb.servers;

import org.junit.Test;
import static org.junit.Assert.*;

public class EchoServerTest {
    @Test public void testNetworking() {

    }
}
